version: "3"

services:
  app:
    image: golang:latest
    volumes:
      - $PWD:/go/src/github.com/learn-go
    ports:
      - "8800:8800"
    working_dir: /go/src/github.com/learn-go/net-http/
    command:
      - go
      - run
      - .
    networks:
      - go-learn

  database:
    image: mysql:latest
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=go_web"
      - "MYSQL_USER=go_web"
      - "MYSQL_PASSWORD=go_web"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
      - "33061:3306"
    networks:
      - go-learn

volumes:
  db-data:

networks:
  go-learn:
    driver: bridge